# Generated by Django 4.2.5 on 2023-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_options_alter_news_avtor_alter_news_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.FloatField(default=1, verbose_name='Перегляди'),
        ),
    ]
