# Generated by Django 4.2.5 on 2023-10-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_shop_sizes_alter_news_title_alter_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
