# Generated by Django 4.2.5 on 2023-10-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='data',
            new_name='date',
        ),
    ]
